/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppRoot {
    }
    interface AppTodo {
    }
    interface AppTst {
    }
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLAppTodoElement extends Components.AppTodo, HTMLStencilElement {
    }
    var HTMLAppTodoElement: {
        prototype: HTMLAppTodoElement;
        new (): HTMLAppTodoElement;
    };
    interface HTMLAppTstElement extends Components.AppTst, HTMLStencilElement {
    }
    var HTMLAppTstElement: {
        prototype: HTMLAppTstElement;
        new (): HTMLAppTstElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "app-todo": HTMLAppTodoElement;
        "app-tst": HTMLAppTstElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
    }
    interface AppTodo {
    }
    interface AppTst {
    }
    interface IntrinsicElements {
        "app-root": AppRoot;
        "app-todo": AppTodo;
        "app-tst": AppTst;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "app-todo": LocalJSX.AppTodo & JSXBase.HTMLAttributes<HTMLAppTodoElement>;
            "app-tst": LocalJSX.AppTst & JSXBase.HTMLAttributes<HTMLAppTstElement>;
        }
    }
}
